const BackgroundShapes = () => {
  return (
    <div className="absolute bottom-0 left-0 z-0 flex h-full w-full items-end">
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-2 w-full bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4  w-4 border-2 border-blue-300 bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
        <span className="h-2 w-4 bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />

        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
        <span className="h-1 w-full bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="ml-4 grid h-56 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="relative ml-4 grid h-60 w-16 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
      <span className="relative ml-2 grid h-48 w-20 grid-cols-2 items-center justify-items-center gap-1  bg-black p-1">
        <span className="absolute bottom-[100%] left-4 h-4 w-1 border-t-4 border-t-red-700 bg-black" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
        <span className="h-4 w-4  bg-amber-400" />
      </span>
    </div>
  );
};

export default BackgroundShapes;
